# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e1b891124138bfde92262d46c5fb140c3d1e84632302e8e1b967ec15644176aeff9d863a3462ba4f90212612f42cac901b1745f9bf88083d5a57ae7e7e93690

test:
  secret_key_base: 8205566324199ecb565e716e9d401b6b9632800d481a6ba1720e368b5b146f71e58a4298313bd3eff011840c1e0e7ddd48f8a65864fa57dc3a8f49e29a250398

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
